# Generated by Django 4.2.1 on 2023-05-28 15:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulkmail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=1000000, null=True), size=None)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BulkMails',
        ),
    ]
