# Generated by Django 4.2.1 on 2023-05-28 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulkmail', '0002_bulkmail_delete_bulkmails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkmail',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='bulkmail',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=1000000), blank=True, null=True, size=None),
        ),
    ]
